export const privacyPolicyTranslations = {
  es: {
    title: "Política de Privacidad",
    content: `<p>Esta Política de Privacidad establece los términos en que INXORA, con RUC 20603436475 (TECNOTOTAL S.A.C.), utiliza y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web. Esta compañía está comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de información personal con la cual usted pueda ser identificado, lo hacemos asegurando que sólo se empleará de acuerdo con los términos de este documento.</p>
<h2>Información que es recogida</h2>
<p>Nuestro sitio web podrá recoger información personal, por ejemplo: Nombre, información de contacto como su dirección de correo electrónico e información demográfica. Así mismo, cuando sea necesario podrá ser requerida información específica para procesar algún pedido o realizar una entrega o facturación.</p>
<h2>Uso de la información recogida</h2>
<p>Nuestro sitio web emplea la información con el fin de proporcionar el mejor servicio posible, particularmente para mantener un registro de usuarios, de pedidos en caso que aplique, y mejorar nuestros productos y servicios. Es posible que sean enviados correos electrónicos periódicamente a través de nuestro sitio con ofertas especiales, nuevos productos y otra información publicitaria que consideremos relevante para usted o que pueda brindarle algún beneficio, estos correos electrónicos serán enviados a la dirección que usted proporcione y podrán ser cancelados en cualquier momento.</p>
<p>INXORA está altamente comprometido para cumplir con el compromiso de mantener su información segura. Usamos los sistemas más avanzados y los actualizamos constantemente para asegurarnos que no exista ningún acceso no autorizado.</p>
<h2>Cookies</h2>
<p>Una cookie se refiere a un fichero que es enviado con la finalidad de solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero se crea y la cookie sirve entonces para tener información respecto al tráfico web, y también facilita las futuras visitas a una web recurrente. Otra función que tienen las cookies es que con ellas las webs pueden reconocerte individualmente y por tanto brindarte el mejor servicio personalizado de su web.</p>
<p>Nuestro sitio web emplea las cookies para poder identificar las páginas que son visitadas y su frecuencia. Esta información es empleada únicamente para análisis estadístico y después la información se elimina de forma permanente. Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin embargo, las cookies ayudan a proporcionar un mejor servicio de los sitios web, éstas no dan acceso a información de su ordenador ni de usted, a menos de que usted así lo quiera y la proporcione directamente. Usted puede aceptar o negar el uso de cookies, sin embargo, la mayoría de navegadores aceptan cookies automáticamente pues sirve para tener un mejor servicio web. También usted puede cambiar la configuración de su ordenador para declinar las cookies. Si se declinan es posible que no pueda utilizar algunos de nuestros servicios.</p>
<h2>Enlaces a Terceros</h2>
<p>Este sitio web pudiera contener enlaces a otros sitios que pudieran ser de su interés. Una vez que usted haga clic en estos enlaces y abandone nuestra página, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los términos o privacidad ni de la protección de sus datos en esos otros sitios terceros. Dichos sitios están sujetos a sus propias políticas de privacidad por lo cual es recomendable que los consulte para confirmar que usted está de acuerdo con estas.</p>
<h2>Control de su información personal</h2>
<p>En cualquier momento usted puede restringir la recopilación o el uso de la información personal que es proporcionada a nuestro sitio web. Cada vez que se le solicite rellenar un formulario, como el de alta de usuario, puede marcar o desmarcar la opción de recibir información por correo electrónico. En caso de que haya marcado la opción de recibir nuestro boletín o publicidad usted puede cancelarla en cualquier momento.</p>
<p>Esta compañía no venderá, cederá ni distribuirá la información personal que es recopilada sin su consentimiento, salvo que sea requerido por un juez con una orden judicial.</p>
<p>INXORA se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.</p>`
  },
  en: {
    title: "Privacy Policy",
    content: `<p>This Privacy Policy sets out how INXORA, with RUC 20603436475 (TECNOTOTAL S.A.C.), uses and protects any information that you give when you use this website. INXORA is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</p>
<h2>Information Collected</h2>
<p>Our website may collect personal information such as your name, contact information including your email address, and demographic information. Specific information may also be required to process an order or to make a delivery or billing.</p>
<h2>Use of Collected Information</h2>
<p>Our website uses the information in order to provide the best possible service, particularly to maintain a user registry, of orders if applicable, and to improve our products and services. Periodically, emails may be sent through our site with special offers, new products, and other advertising information which we think you may find interesting. These emails will be sent to the address you provide and can be canceled at any time.</p>
<p>INXORA is highly committed to fulfilling the commitment to keep your information secure. We use the most advanced systems and update them constantly to ensure that there is no unauthorized access.</p>
<h2>Cookies</h2>
<p>A cookie refers to a file that is sent with the purpose of requesting permission to be stored on your computer. By accepting such a file, the cookie is created and is then used to have information regarding web traffic, and also facilitates future visits to a recurring website. Another function that cookies have is that with them websites can recognize you individually and therefore provide the best personalized service on their website.</p>
<p>Our website uses cookies to identify the pages that are visited and their frequency. This information is used only for statistical analysis and then the information is permanently deleted. You can delete cookies at any time from your computer. However, cookies help to provide a better service for websites, they do not give access to information from your computer or from you, unless you want it and provide it directly. You can accept or decline the use of cookies, however, the majority of browsers accept cookies automatically as it serves to have a better web service. You can also change your computer settings to decline cookies. If declined, you may not be able to use some of our services.</p>
<h2>Links to Third Parties</h2>
<p>This website may contain links to other sites that may be of your interest. Once you click on these links and leave our page, we no longer have control over the site to which you are redirected and therefore are not responsible for the terms or privacy or the protection of your data on those other third-party sites. Such sites are subject to their own privacy policies, so it is recommended that you consult them to confirm that you agree with them.</p>
<h2>Controlling your personal information</h2>
<p>At any time you may restrict the collection or use of personal information that is provided to our website. Whenever you are asked to fill in a form, such as user registration, you can check or uncheck the option to receive information by email. If you have opted in to receive our newsletter or advertising, you can cancel it at any time.</p>
<p>This company will not sell, assign or distribute the personal information that is collected without your consent, unless required by a judge with a court order.</p>
<p>INXORA reserves the right to change the terms of this Privacy Policy at any time.</p>`
  },
  pt: {
    title: "Política de Privacidade",
    content: `<p>Esta Política de Privacidade estabelece os termos em que a INXORA, com RUC 20603436475 (TECNOTOTAL S.A.C.), utiliza e protege as informações fornecidas por seus usuários ao utilizar seu site. Esta empresa está comprometida com a segurança dos dados de seus usuários. Quando solicitamos que você preencha os campos de informações pessoais com as quais possa ser identificado, fazemos isso garantindo que serão usadas apenas de acordo com os termos deste documento.</p>
<h2>Informações que são coletadas</h2>
<p>Nosso site pode coletar informações pessoais, por exemplo: Nome, informações de contato como seu endereço de e-mail e informações demográficas. Da mesma forma, quando necessário, podem ser solicitadas informações específicas para processar algum pedido ou realizar uma entrega ou faturamento.</p>
<h2>Uso das informações coletadas</h2>
<p>Nosso site utiliza as informações para fornecer o melhor serviço possível, especialmente para manter um registro de usuários, de pedidos quando aplicável, e melhorar nossos produtos e serviços. É possível que sejam enviados e-mails periodicamente através do nosso site com ofertas especiais, novos produtos e outras informações publicitárias que consideremos relevantes para você ou que possam lhe trazer algum benefício. Esses e-mails serão enviados para o endereço que você fornecer e poderão ser cancelados a qualquer momento.</p>
<p>A INXORA está altamente comprometida em cumprir o compromisso de manter suas informações seguras. Usamos os sistemas mais avançados e os atualizamos constantemente para garantir que não haja nenhum acesso não autorizado.</p>
<h2>Cookies</h2>
<p>Um cookie refere-se a um arquivo que é enviado com a finalidade de solicitar permissão para ser armazenado em seu computador. Ao aceitar tal arquivo, o cookie é criado e serve então para ter informações sobre o tráfego da web, e também facilita futuras visitas a um site recorrente. Outra função dos cookies é que com eles os sites podem reconhecê-lo individualmente e, portanto, oferecer o melhor serviço personalizado do seu site.</p>
<p>Nosso site utiliza cookies para identificar as páginas que são visitadas e sua frequência. Essas informações são usadas apenas para análise estatística e depois a informação é eliminada permanentemente. Você pode eliminar os cookies a qualquer momento do seu computador. No entanto, os cookies ayudan a fornecer um melhor serviço dos sites, eles não dão acesso a informações do seu computador ou de você, a menos que você queira e forneça diretamente. Você pode aceitar ou recusar el uso de cookies, no entanto, a maioria dos navegadores aceita cookies automaticamente, pois serve para ter um melhor serviço web. Você também pode alterar as configurações do seu computador para recusar cookies. Se recusados, é possível que não possa utilizar alguns dos nossos serviços.</p>
<h2>Links para Terceiros</h2>
<p>Este site pode conter links para outros sites que possam ser do seu interesse. Uma vez que você clique nesses links e saia da nossa página, não temos mais controle sobre o site para o qual é redirecionado e, portanto, não somos responsáveis pelos termos ou privacidade nem pela proteção de seus dados nesses outros sitios de terceiros. Esses sites estão sujetos às suas próprias políticas de privacidade, por isso é recomendável que você as consulte para confirmar que você está de acordo com elas.</p>
<h2>Controle de suas informações pessoais</h2>
<p>A qualquer momento você pode restringir a coleta ou o uso das informações pessoais fornecidas ao nosso site. Sempre que for solicitado preencher um formulário, como o de cadastro de usuário, você pode marcar ou desmarcar a opção de receber informações por e-mail. Caso tenha optado por receber nosso boletim informativo ou publicidade, você pode cancelá-lo a qualquer momento.</p>
<p>Esta empresa não venderá, cederá ou distribuirá as informações pessoais que são coletadas sem o seu consentimento, salvo se for exigido por um juiz com uma ordem judicial.</p>
<p>A INXORA reserva-se o direito de alterar os termos desta Política de Privacidade a qualquer momento.</p>`
  },
}
