export const libroReclamacionesTranslation = {
  es: {
    title: "Libro de Reclamaciones",
    subtitle: "Conforme a la Ley N° 29571, ponemos a tu disposición nuestro Libro de Reclamaciones Virtual. Completa el siguiente formulario para registrar tu reclamo o queja. Nos comprometemos a responder en un plazo no mayor a 15 días hábiles.",
    atras: "← Atrás",
    exito: "¡Tu reclamo ha sido enviado correctamente! Nos pondremos en contacto contigo a la brevedad.",
    enviando: "Enviando...",
    datosConsumidor: "Datos del consumidor reclamante",
    detalleReclamo: "Detalle del reclamo",
    nombre: "Nombre *",
    primerApellido: "Primer Apellido *",
    segundoApellido: "Segundo Apellido",
    tipoDocumento: "Tipo de Documento *",
    numeroDocumento: "Número de Documento *",
    celular: "Celular *",
    departamento: "Departamento *",
    provincia: "Provincia",
    distrito: "Distrito",
    direccion: "Dirección *",
    referencia: "Referencia",
    correoElectronico: "Correo electrónico *",
    menorEdad: "¿Eres menor de edad?",
    nombreTutor: "Nombre del Tutor",
    correoTutor: "Correo del Tutor",
    tipoDocumentoTutor: "Tipo de Documento del Tutor",
    numeroDocumentoTutor: "Número de Documento del Tutor",
    tipoReclamo: "Tipo de reclamo *",
    tipoConsumo: "Tipo de consumo *",
    numeroPedido: "N° de pedido *",
    fechaReclamo: "Fecha de reclamo/queja",
    proveedor: "Proveedor",
    montoReclamado: "Monto reclamado (S/.)",
    descripcionProducto: "Descripción del producto o servicio *",
    fechaCompra: "Fecha de compra",
    fechaConsumo: "Fecha de consumo",
    fechaCaducidad: "Fecha de caducidad",
    detalleReclamacion: "Detalle de la Reclamación / Queja *",
    pedidoCliente: "Pedido del Cliente *",
    enviarReclamo: "Enviar Reclamo",
    selecciona: "Selecciona",
    si: "Sí",
    no: "No",
    reclamacion: "Reclamación",
    queja: "Queja",
    producto: "Producto",
    servicio: "Servicio",
    dni: "DNI",
    ce: "CE",
    pasaporte: "Pasaporte",
    ruc: "RUC",
    validaciones: {
      camposObligatorios: "Por favor, completa todos los campos obligatorios y acepta los términos.",
      telefonoFormato: "El celular debe tener exactamente 9 dígitos",
      emailInvalido: "Correo electrónico inválido",
      documentoInvalido: "Número de documento inválido"
    },
    avisosLegales: {
      linea1: "* La formulación del reclamo no excluye el recurso a otros medios de resolución de controversias ni es un requisito previo para presentar una denuncia ante el Indecopi.",
      linea2: "* El proveedor debe responder a la reclamación en un plazo no superior a quince (15) días naturales, pudiendo ampliar el plazo hasta quince días.",
      linea3: "* Con la firma de este documento, el cliente autoriza a ser contactado después de la tramitación de la reclamación para evaluar la calidad y satisfacción del proceso de atención de reclamaciones."
    },
    politicaPrivacidad: "He leído y acepto la Política de Privacidad y la Política de Cookies.",
    departamentos: [
      "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"
    ]
  },
  en: {
    title: "Complaints Book",
    subtitle: "In accordance with Law No. 29571, we make our Virtual Complaints Book available to you. Complete the following form to register your complaint or claim. We commit to respond within no more than 15 business days.",
    atras: "← Back",
    exito: "Your complaint has been sent successfully! We will contact you shortly.",
    enviando: "Sending...",
    datosConsumidor: "Complainant consumer data",
    detalleReclamo: "Complaint details",
    nombre: "Name *",
    primerApellido: "First Last Name *",
    segundoApellido: "Second Last Name",
    tipoDocumento: "Document Type *",
    numeroDocumento: "Document Number *",
    celular: "Mobile *",
    departamento: "Department *",
    provincia: "Province",
    distrito: "District",
    direccion: "Address *",
    referencia: "Reference",
    correoElectronico: "Email *",
    menorEdad: "Are you under 18?",
    nombreTutor: "Tutor's Name",
    correoTutor: "Tutor's Email",
    tipoDocumentoTutor: "Tutor's Document Type",
    numeroDocumentoTutor: "Tutor's Document Number",
    tipoReclamo: "Complaint type *",
    tipoConsumo: "Consumption type *",
    numeroPedido: "Order number *",
    fechaReclamo: "Complaint/claim date",
    proveedor: "Provider",
    montoReclamado: "Claimed amount (S/.)",
    descripcionProducto: "Product or service description *",
    fechaCompra: "Purchase date",
    fechaConsumo: "Consumption date",
    fechaCaducidad: "Expiration date",
    detalleReclamacion: "Complaint/Claim Details *",
    pedidoCliente: "Client Order *",
    enviarReclamo: "Send Complaint",
    selecciona: "Select",
    si: "Yes",
    no: "No",
    reclamacion: "Claim",
    queja: "Complaint",
    producto: "Product",
    servicio: "Service",
    dni: "DNI",
    ce: "CE",
    pasaporte: "Passport",
    ruc: "RUC",
    validaciones: {
      camposObligatorios: "Please complete all required fields and accept the terms.",
      telefonoFormato: "Mobile must have exactly 9 digits",
      emailInvalido: "Invalid email address",
      documentoInvalido: "Invalid document number"
    },
    avisosLegales: {
      linea1: "* Filing a complaint does not exclude the use of other means of dispute resolution nor is it a prerequisite for filing a complaint with Indecopi.",
      linea2: "* The provider must respond to the complaint within no more than fifteen (15) calendar days, and may extend the period for up to fifteen days.",
      linea3: "* By signing this document, the customer authorizes to be contacted after the complaint process to assess the quality and satisfaction of the complaint handling process."
    },
    politicaPrivacidad: "I have read and accept the Privacy Policy and the Cookies Policy.",
    departamentos: [
      "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"
    ]
  },
  pt: {
    title: "Livro de Reclamações",
    subtitle: "De acordo com a Lei nº 29571, disponibilizamos nosso Livro de Reclamações Virtual. Preencha o formulário a seguir para registrar sua reclamação ou queixa. Comprometemo-nos a responder em no máximo 15 dias úteis.",
    atras: "← Voltar",
    exito: "Sua reclamação foi enviada com sucesso! Entraremos em contato em breve.",
    enviando: "Enviando...",
    datosConsumidor: "Dados do consumidor reclamante",
    detalleReclamo: "Detalhes da reclamação",
    nombre: "Nome *",
    primerApellido: "Primeiro Sobrenome *",
    segundoApellido: "Segundo Sobrenome",
    tipoDocumento: "Tipo de Documento *",
    numeroDocumento: "Número do Documento *",
    celular: "Celular *",
    departamento: "Departamento *",
    provincia: "Província",
    distrito: "Distrito",
    direccion: "Endereço *",
    referencia: "Referência",
    correoElectronico: "E-mail *",
    menorEdad: "Você é menor de idade?",
    nombreTutor: "Nome do Tutor",
    correoTutor: "E-mail do Tutor",
    tipoDocumentoTutor: "Tipo de Documento do Tutor",
    numeroDocumentoTutor: "Número do Documento do Tutor",
    tipoReclamo: "Tipo de reclamação *",
    tipoConsumo: "Tipo de consumo *",
    numeroPedido: "Nº do pedido *",
    fechaReclamo: "Data da reclamação/queixa",
    proveedor: "Fornecedor",
    montoReclamado: "Valor reclamado (S/.)",
    descripcionProducto: "Descrição do produto ou serviço *",
    fechaCompra: "Data da compra",
    fechaConsumo: "Data do consumo",
    fechaCaducidad: "Data de validade",
    detalleReclamacion: "Detalhes da Reclamação / Queixa *",
    pedidoCliente: "Pedido do Cliente *",
    enviarReclamo: "Enviar Reclamação",
    selecciona: "Selecione",
    si: "Sim",
    no: "Não",
    reclamacion: "Reclamação",
    queja: "Queixa",
    producto: "Produto",
    servicio: "Serviço",
    dni: "DNI",
    ce: "CE",
    pasaporte: "Passaporte",
    ruc: "RUC",
    validaciones: {
      camposObligatorios: "Por favor, preencha todos os campos obrigatórios e aceite os termos.",
      telefonoFormato: "O celular deve ter exatamente 9 dígitos",
      emailInvalido: "E-mail inválido",
      documentoInvalido: "Número de documento inválido"
    },
    avisosLegales: {
      linea1: "* O registro da reclamação não exclui o uso de outros meios de resolução de disputas nem é um pré-requisito para apresentar uma reclamação ao Indecopi.",
      linea2: "* O fornecedor deve responder à reclamação em no máximo quinze (15) dias corridos, podendo prorrogar o prazo por até quinze dias.",
      linea3: "* Ao assinar este documento, o cliente autoriza ser contatado após o processo de reclamação para avaliar a qualidade e satisfação do atendimento da reclamação."
    },
    politicaPrivacidad: "Li e aceito a Política de Privacidade e a Política de Cookies.",
    departamentos: [
      "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"
    ]
  }
};
